version: "0.2"
language: en
dictionaries:
  - css
  - html
  - typescript
enableFiletypes:
  - ignore
  - properties
  - svelte
  - xml
files:
  - "**/.*"
  - "**/*.{css,js,json,jsonc,html,md,svelte,svg,yaml,yml,xml}"
useGitignore: true
ignorePaths:
  - pnpm-lock.yaml
  - package/**
  - src/**/*.test.js
  - src/routes/locales/**/*.yaml
words:
  - Bonjour
  - cooldown
  - dimanche
  - GHSA
  - Ghsas
  - Kohei
  - messageformat
  - oxlint
  - subtag
  - Sveltia
  - unrs
  - Vite
  - Yoshino
overrides:
  - language: en-gb
    filename: "**/*.md"
